export enum ChainsEnum {
  ETH = 'Ethereum',
  BSC = 'BSC',
  XDAI = 'Gnosis',
  MATIC = 'Polygon',
  FTM = 'Fantom',
  OKT = 'OEC',
  HECO = 'HECO',
  AVAX = 'Avalanche',
  OP = 'Optimism',
  ARB = 'Arbitrum',
  CELO = 'Celo',
  MOVR = 'Moonriver',
  CRO = 'Cronos',
  BOBA = 'Boba',
  METIS = 'Metis',
  BTT = 'BitTorrent',
  AURORA = 'Aurora',
  MOBM = 'Moonbeam',
  SBCH = 'SmartBch',
  FUSE = 'Fuse',
  HMY = 'Harmony',
  KLAY = 'Klaytn',
  ASTAR = 'Astar',
  SDN = 'Shiden',
  PALM = 'Palm',
  IOTX = 'IoTeX',
  RSK = 'RSK',
  WAN = 'Wanchain',
  KCC = 'KCC',
  SGB = 'Songbird',
  EVMOS = 'EvmOS',
  DFK = 'DFK',
  TLOS = 'Telos',
  SWM = 'Swimmer',
  NOVA = 'Arbitrum Nova',
  PLS = 'Pulse Chain',
}

export const chainIds: Record<string, number> = {
  eth: 1,
  bsc: 56,
  avax: 43114,
  matic: 137,
  arb: 42161,
  ganache: 1337,
  hardhat: 31337,
};
